### ISSUE TITLE
overflow bug while parsing an invalid device interface path

### ISSUE THREAD

**Issue by 5chdn** [dcuddeback/libusb-sys#9]
The crash is caused by an overflow when trying to set the unsigned integer length to a negative number while parsing an invalid device interface path.

- Initial issue https://github.com/paritytech/parity/issues/6230
- Patch available in https://github.com/paritytech/libusb-sys/pull/1

Please let me know what you think about the patch, eventually can create an upstream PR.

**Comment by dcuddeback** [comment]
@5chdn That doesn't appear to have anything to do with this project. There is no `windows_usb.c` in this repo. Perhaps you meant to report this to a different upstream project?

**Comment by 5chdn** [comment]
Ok, I was just following the Github-forks "upstream", sorry for the noise.
